[metadata]
name = "Lake Dweller"
origin_url = "https://github.com/yourusername/lake-dweller.nvim"

[colors]
foreground = "#d8d8d8"
background = "#0e0e16"

cursor_bg = "#d8d8d8"
cursor_fg = "#1f2430"
cursor_border = "#d8d8d8"

selection_bg = "#858d95"
selection_fg = "#1f2430"

scrollbar_thumb = "#858d95"
split = "#858d95"

ansi = [
  "#101010", # 0 black
  "#ef6f6f", # 1 red
  "#8ac490", # 2 green
  "#d8c6a0", # 3 yellow (beige)
  "#adc7e6", # 4 blue
  "#d58ca6", # 5 magenta (rosy-pink)
  "#8abbb4", # 6 cyan
  "#d8d8d8", # 7 white (light-grey)
]

brights = [
  "#858d95", # 8 bright black (slate)
  "#ef6f6f", # 9 bright red
  "#8ac490", # 10 bright green
  "#e0d2b6", # 11 bright yellow (lighter beige)
  "#adc7e6", # 12 bright blue
  "#d58ca6", # 13 bright magenta
  "#8abbb4", # 14 bright cyan
  "#f0f0f0", # 15 bright white (new off-white)
]

[colors.tab_bar]
background = "#1f2430"

[colors.tab_bar.active_tab]
bg_color = "#d8d8d8"
fg_color = "#1f2430"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#1f2430"
fg_color = "#858d95"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1f2430"
fg_color = "#d8d8d8"
italic = true

[colors.tab_bar.new_tab]
bg_color = "#1f2430"
fg_color = "#858d95"

[colors.tab_bar.new_tab_hover]
bg_color = "#1f2430"
fg_color = "#d8d8d8"
italic = true
